#include "ModelImporter.h"
#include <cstring>

namespace {
QString unquote(QString value){value=value.trimmed();if(value.startsWith('"')&&value.endsWith('"'))value=value.mid(1,value.size()-2);return value;}
QString mtlTexturePath(const QString &value){QStringList parts=value.trimmed().split(QRegularExpression("\\s+"),Qt::SkipEmptyParts);int first=0;while(first<parts.size()&&parts[first].startsWith('-')){++first;if(first<parts.size()&&!parts[first].startsWith('-'))++first;}return unquote(parts.mid(first).join(' '));}
QString cacheImage(const QString &modelPath,int index,const QByteArray &bytes,const QString &mime){if(bytes.isEmpty())return {};QString suffix=mime.contains("jpeg",Qt::CaseInsensitive)?"jpg":mime.contains("webp",Qt::CaseInsensitive)?"webp":mime.contains("tga",Qt::CaseInsensitive)?"tga":"png";const QString root=QDir(QStandardPaths::writableLocation(QStandardPaths::CacheLocation)).filePath("model-textures");QDir().mkpath(root);const QString key=QString::fromLatin1(QCryptographicHash::hash((modelPath+QString::number(index)).toUtf8(),QCryptographicHash::Sha1).toHex());const QString filePath=QDir(root).filePath(key+"."+suffix);QFile file(filePath);if(file.open(QIODevice::WriteOnly)){file.write(bytes);return filePath;}return {};}
void appendMtl(const QString &path,ModelAsset &asset){QFile file(path);if(!file.open(QIODevice::ReadOnly|QIODevice::Text))return;QString material=QFileInfo(path).completeBaseName();const QHash<QString,QString> mapSlots{{"map_Kd","Base Color"},{"map_Bump","Normal"},{"bump","Normal"},{"map_d","Opacity"},{"map_Pr","Roughness"},{"map_Pm","Metallic"},{"map_Ke","Emission"}};while(!file.atEnd()){const QString line=QString::fromUtf8(file.readLine()).trimmed();if(line.startsWith("newmtl ")){material=line.mid(7).trimmed();continue;}for(auto it=mapSlots.cbegin();it!=mapSlots.cend();++it)if(line.startsWith(it.key()+" ")){const QString relative=mtlTexturePath(line.mid(it.key().size()+1));asset.textures.push_back({material,it.value(),QDir(QFileInfo(path).absolutePath()).filePath(relative)});break;}}}
bool readGlb(const QString &path,QByteArray &json,QByteArray &bin,QString &error){QFile file(path);if(!file.open(QIODevice::ReadOnly)){error="Cannot read GLB file.";return false;}const QByteArray source=file.readAll();if(source.size()<20||qFromLittleEndian<quint32>(reinterpret_cast<const uchar*>(source.constData()))!=0x46546c67){error="Invalid GLB header.";return false;}int position=12;while(position+8<=source.size()){const quint32 length=qFromLittleEndian<quint32>(reinterpret_cast<const uchar*>(source.constData()+position));const quint32 type=qFromLittleEndian<quint32>(reinterpret_cast<const uchar*>(source.constData()+position+4));position+=8;if(length>quint32(source.size()-position)){error="Invalid GLB chunk.";return false;}const QByteArray chunk=source.mid(position,length);position+=length;if(type==0x4e4f534a)json=chunk;else if(type==0x004e4942)bin=chunk;}if(json.isEmpty()){error="GLB JSON chunk is missing.";return false;}return true;}
QByteArray bufferData(const QJsonArray &buffers,const QJsonArray &views,int viewIndex,const QString &modelPath,const QByteArray &glbBin){if(viewIndex<0||viewIndex>=views.size())return {};const QJsonObject view=views[viewIndex].toObject();const int bufferIndex=view.value("buffer").toInt(-1);if(bufferIndex<0||bufferIndex>=buffers.size())return {};const QJsonObject buffer=buffers[bufferIndex].toObject();QByteArray data;if(bufferIndex==0&&!glbBin.isEmpty())data=glbBin;else{const QString uri=buffer.value("uri").toString();if(uri.startsWith("data:")){const int comma=uri.indexOf(',');if(comma>=0)data=QByteArray::fromBase64(uri.mid(comma+1).toLatin1());}else{QFile file(QDir(QFileInfo(modelPath).absolutePath()).filePath(QUrl::fromPercentEncoding(uri.toUtf8())));if(file.open(QIODevice::ReadOnly))data=file.readAll();}}const int offset=view.value("byteOffset").toInt();const int length=view.value("byteLength").toInt();return offset>=0&&length>0&&offset+length<=data.size()?data.mid(offset,length):QByteArray{};}
QVector<float> floatAccessor(const QJsonArray &accessors,const QJsonArray &views,const QJsonArray &buffers,int accessorIndex,const QString &path,const QByteArray &bin,int &components){components=0;if(accessorIndex<0||accessorIndex>=accessors.size())return {};const QJsonObject accessor=accessors[accessorIndex].toObject();if(accessor.value("componentType").toInt()!=5126)return {};const QString type=accessor.value("type").toString();components=type=="VEC2"?2:type=="VEC3"?3:type=="VEC4"?4:1;const int count=accessor.value("count").toInt();const int viewIndex=accessor.value("bufferView").toInt(-1);QByteArray source=bufferData(buffers,views,viewIndex,path,bin);if(source.isEmpty())return {};const QJsonObject view=views[viewIndex].toObject();const int stride=view.value("byteStride").toInt(components*4),offset=accessor.value("byteOffset").toInt();QVector<float> result;result.reserve(count*components);for(int row=0;row<count;++row){const int base=offset+row*stride;if(base+components*4>source.size())return {};for(int c=0;c<components;++c){float value;memcpy(&value,source.constData()+base+c*4,sizeof value);result<<value;}}return result;}
QVector<int> indexAccessor(const QJsonArray &accessors,const QJsonArray &views,const QJsonArray &buffers,int accessorIndex,const QString &path,const QByteArray &bin){if(accessorIndex<0||accessorIndex>=accessors.size())return {};const QJsonObject accessor=accessors[accessorIndex].toObject();const int component=accessor.value("componentType").toInt(),bytes=component==5121?1:component==5123?2:component==5125?4:0;if(!bytes)return {};const int viewIndex=accessor.value("bufferView").toInt(-1);QByteArray source=bufferData(buffers,views,viewIndex,path,bin);if(source.isEmpty())return {};const QJsonObject view=views[viewIndex].toObject();const int stride=view.value("byteStride").toInt(bytes),offset=accessor.value("byteOffset").toInt(),count=accessor.value("count").toInt();QVector<int> result;result.reserve(count);for(int row=0;row<count;++row){const int base=offset+row*stride;if(base+bytes>source.size())return {};if(bytes==1)result<<uchar(source[base]);else if(bytes==2)result<<qFromLittleEndian<quint16>(reinterpret_cast<const uchar*>(source.constData()+base));else result<<int(qFromLittleEndian<quint32>(reinterpret_cast<const uchar*>(source.constData()+base)));}return result;}
bool loadGltf(const QString &path,const QByteArray &json,const QByteArray &glbBin,ModelAsset &asset,QString &error){QJsonParseError parse;const QJsonDocument document=QJsonDocument::fromJson(json,&parse);if(parse.error!=QJsonParseError::NoError||!document.isObject()){error="Invalid glTF JSON.";return false;}const QJsonObject root=document.object();const QJsonArray accessors=root.value("accessors").toArray(),meshes=root.value("meshes").toArray(),images=root.value("images").toArray(),textures=root.value("textures").toArray(),buffers=root.value("buffers").toArray(),views=root.value("bufferViews").toArray();for(const auto mesh:meshes)for(const auto primitive:mesh.toObject().value("primitives").toArray()){const QJsonObject value=primitive.toObject();const QJsonObject attributes=value.value("attributes").toObject();int positionComponents=0,uvComponents=0;const QVector<float> positions=floatAccessor(accessors,views,buffers,attributes.value("POSITION").toInt(-1),path,glbBin,positionComponents);const QVector<float> uvs=floatAccessor(accessors,views,buffers,attributes.value("TEXCOORD_0").toInt(-1),path,glbBin,uvComponents);if(positionComponents!=3||positions.isEmpty())continue;const int vertexCount=positions.size()/3,base=asset.vertices.size(),material=value.value("material").toInt(-1);asset.vertexCount+=vertexCount;for(int i=0;i<vertexCount;++i){const QVector2D uv=uvComponents>=2&&uvs.size()>=i*uvComponents+2?QVector2D(uvs[i*uvComponents],uvs[i*uvComponents+1]):QVector2D{};asset.vertices.push_back({QVector3D(positions[i*3],positions[i*3+1],positions[i*3+2]),uv});}QVector<int> indices=indexAccessor(accessors,views,buffers,value.value("indices").toInt(-1),path,glbBin);if(indices.isEmpty())for(int i=0;i<vertexCount;++i)indices<<i;for(int i=0;i+2<indices.size();i+=3)if(indices[i]>=0&&indices[i+1]>=0&&indices[i+2]>=0&&indices[i]<vertexCount&&indices[i+1]<vertexCount&&indices[i+2]<vertexCount)asset.triangles.push_back({base+indices[i],base+indices[i+1],base+indices[i+2],material});}asset.faceCount=asset.triangles.size();
 QVector<QString> resolvedImages;resolvedImages.reserve(images.size());for(int i=0;i<images.size();++i){const QJsonObject image=images[i].toObject();const QString uri=image.value("uri").toString();if(!uri.isEmpty()&&!uri.startsWith("data:")){resolvedImages<<QDir(QFileInfo(path).absolutePath()).filePath(QUrl::fromPercentEncoding(uri.toUtf8()));continue;}QByteArray data;if(uri.startsWith("data:")){const int comma=uri.indexOf(',');if(comma>=0)data=QByteArray::fromBase64(uri.mid(comma+1).toLatin1());}else data=bufferData(buffers,views,image.value("bufferView").toInt(-1),path,glbBin);resolvedImages<<cacheImage(path,i,data,image.value("mimeType").toString());}
 auto imagePath=[&](int textureIndex){if(textureIndex<0||textureIndex>=textures.size())return QString{};const int source=textures[textureIndex].toObject().value("source").toInt(-1);return source>=0&&source<resolvedImages.size()?resolvedImages[source]:QString{};};for(const auto material:root.value("materials").toArray()){const QJsonObject object=material.toObject();const QString name=object.value("name").toString("Material");const QJsonObject pbr=object.value("pbrMetallicRoughness").toObject();const QHash<QString,QJsonObject> entries{{"Base Color",pbr.value("baseColorTexture").toObject()},{"Metallic Roughness",pbr.value("metallicRoughnessTexture").toObject()},{"Normal",object.value("normalTexture").toObject()},{"Occlusion",object.value("occlusionTexture").toObject()},{"Emission",object.value("emissiveTexture").toObject()}};for(auto it=entries.cbegin();it!=entries.cend();++it){const QString texture=imagePath(it.value().value("index").toInt(-1));if(!texture.isEmpty())asset.textures.push_back({name,it.key(),texture});}}return true;}
struct FbxValue { QString text; QByteArray bytes; QVector<double> numbers; bool numeric=false; double number=0.; };
struct FbxNode { QString name; QVector<FbxValue> values; QVector<FbxNode> children; };

template <typename T> bool fbxRead(const QByteArray &source,qsizetype &offset,T &value){
    if(offset<0||offset+qsizetype(sizeof(T))>source.size())return false;
    memcpy(&value,source.constData()+offset,sizeof(T));offset+=sizeof(T);return true;
}

bool fbxInflate(const QByteArray &compressed,quint32 unpacked,QByteArray &out){
    using Uncompress=int (__cdecl *)(unsigned char *,unsigned long *,const unsigned char *,unsigned long);
    static const Uncompress uncompress=[] { return reinterpret_cast<Uncompress>(QLibrary::resolve("Qt6Core","z_uncompress")); }();
    if(!uncompress||unpacked>quint32(std::numeric_limits<int>::max()))return false;
    out=QByteArray(int(unpacked),Qt::Uninitialized);unsigned long length=unpacked;
    return uncompress(reinterpret_cast<unsigned char *>(out.data()),&length,reinterpret_cast<const unsigned char *>(compressed.constData()),unsigned long(compressed.size()))==0&&length==unpacked;
}

bool fbxValue(const QByteArray &source,qsizetype &offset,FbxValue &value,QString &error){
    char type=0;if(!fbxRead(source,offset,type)){error="Truncated FBX property.";return false;}
    auto fixed=[&](auto &number){if(!fbxRead(source,offset,number)){error="Truncated FBX scalar.";return false;}value.numeric=true;value.number=number;value.numbers<<double(number);return true;};
    if(type=='Y'){qint16 v;return fixed(v);} if(type=='I'){qint32 v;return fixed(v);} if(type=='L'){qint64 v;return fixed(v);} if(type=='F'){float v;return fixed(v);} if(type=='D'){double v;return fixed(v);} if(type=='C'){quint8 v;return fixed(v);}
    if(type=='S'||type=='R'){quint32 length=0;if(!fbxRead(source,offset,length)||offset+length>source.size()){error="Invalid FBX string/blob.";return false;}const QByteArray data=source.mid(offset,length);offset+=length;if(type=='S')value.text=QString::fromUtf8(data);else value.bytes=data;return true;}
    const int bytes=type=='d'||type=='l'?8:type=='f'||type=='i'?4:type=='b'?1:0;
    if(!bytes){error=QString("Unsupported FBX property type '%1'.").arg(type);return false;}
    quint32 count=0,encoding=0,length=0;if(!fbxRead(source,offset,count)||!fbxRead(source,offset,encoding)||!fbxRead(source,offset,length)||offset+length>source.size()){error="Invalid FBX array.";return false;}
    QByteArray raw=source.mid(offset,length);offset+=length;const quint64 expected=quint64(count)*quint64(bytes);
    if(expected>quint64(std::numeric_limits<int>::max())){error="FBX array is too large.";return false;}
    if(encoding==1){QByteArray decoded;if(!fbxInflate(raw,quint32(expected),decoded)){error="Unable to decompress an FBX array.";return false;}raw=decoded;}else if(encoding!=0||raw.size()!=int(expected)){error="Invalid FBX array encoding.";return false;}
    value.numbers.reserve(int(count));for(quint32 i=0;i<count;++i){const char *data=raw.constData()+i*bytes;if(type=='d'){double v;memcpy(&v,data,8);value.numbers<<v;}else if(type=='f'){float v;memcpy(&v,data,4);value.numbers<<v;}else if(type=='l'){qint64 v;memcpy(&v,data,8);value.numbers<<double(v);}else if(type=='i'){qint32 v;memcpy(&v,data,4);value.numbers<<double(v);}else value.numbers<<double(uchar(*data));}return true;
}

bool fbxNode(const QByteArray &source,qsizetype &offset,int version,FbxNode &node,QString &error){
    const int header=version>=7500?25:13;if(offset+header>source.size()){error="Truncated FBX node record.";return false;}
    quint64 end=0,properties=0,propertyBytes=0;if(version>=7500){if(!fbxRead(source,offset,end)||!fbxRead(source,offset,properties)||!fbxRead(source,offset,propertyBytes)){error="Invalid FBX 64-bit node.";return false;}}else{quint32 e=0,p=0,b=0;if(!fbxRead(source,offset,e)||!fbxRead(source,offset,p)||!fbxRead(source,offset,b)){error="Invalid FBX node.";return false;}end=e;properties=p;propertyBytes=b;}
    quint8 nameSize=0;if(!fbxRead(source,offset,nameSize)){error="Invalid FBX node name.";return false;}if(end==0&&properties==0&&propertyBytes==0&&nameSize==0)return true;if(end>quint64(source.size())||offset+nameSize>source.size()){error="Invalid FBX node bounds.";return false;}node.name=QString::fromUtf8(source.mid(offset,nameSize));offset+=nameSize;
    const qsizetype propertiesEnd=offset+qsizetype(propertyBytes);if(propertiesEnd>source.size()){error="Invalid FBX property bounds.";return false;}for(quint64 i=0;i<properties;++i){FbxValue value;if(!fbxValue(source,offset,value,error))return false;node.values<<value;}if(offset!=propertiesEnd){error="FBX property list length mismatch.";return false;}
    while(offset<qsizetype(end)){const qsizetype before=offset;FbxNode child;if(!fbxNode(source,offset,version,child,error))return false;if(child.name.isEmpty())break;node.children<<std::move(child);if(offset<=before){error="FBX parser made no progress.";return false;}}if(offset!=qsizetype(end)){error="Invalid FBX child node bounds.";return false;}return true;
}

const FbxNode *fbxChild(const FbxNode &node,const QString &name){for(const auto &child:node.children)if(child.name==name)return &child;return nullptr;}
QVector<double> fbxNumbers(const FbxNode &node,const QString &name){const auto *child=fbxChild(node,name);return child&&!child->values.isEmpty()?child->values.first().numbers:QVector<double>{};}
QString fbxString(const FbxNode &node,const QString &name){const auto *child=fbxChild(node,name);return child&&!child->values.isEmpty()?child->values.first().text:QString{};}
qint64 fbxId(const FbxNode &node){return node.values.isEmpty()?0:qint64(node.values.first().number);}
QString fbxObjectName(const FbxNode &node){return node.values.size()>1?node.values[1].text:QString{};}
QString fbxName(QString value){const int separator=value.indexOf("::");return separator>=0?value.mid(separator+2):value;}

struct FbxGeometry { qint64 id=0;QString name;QVector<QVector3D> positions;QVector<int> polygon;QVector<QVector2D> uv;QVector<int> uvIndices;QVector<int> materialByPolygon; };
struct FbxTexture { qint64 id=0;QString name;QString file;QByteArray content; };

void appendFbxTexture(ModelAsset &asset,const QString &material,QString slot,const QString &path){if(path.isEmpty())return;const QString normalized=QDir::cleanPath(path);for(const auto &entry:asset.textures)if(entry.material==material&&entry.slot==slot&&entry.path==normalized)return;asset.textures.push_back({material,slot,normalized});}
QString fbxSlot(QString property){property=property.toLower();if(property.contains("diffuse")||property.contains("basecolor"))return "Base Color";if(property.contains("normal")||property.contains("bump"))return "Normal";if(property.contains("rough"))return "Roughness";if(property.contains("metal"))return "Metallic";if(property.contains("emiss"))return "Emission";if(property.contains("ambient")||property.contains("occlusion"))return "Ambient Occlusion";if(property.contains("transparen")||property.contains("opacity")||property.contains("alpha"))return "Opacity";if(property.contains("specular")||property.contains("reflect"))return "Specular";return property.isEmpty()?"Texture":property;}

bool buildFbxAsset(const QString &path,const QVector<FbxNode> &roots,ModelAsset &asset,QString &error){
    const FbxNode *objects=nullptr,*connections=nullptr;for(const auto &node:roots){if(node.name=="Objects")objects=&node;else if(node.name=="Connections")connections=&node;}if(!objects){error="FBX Objects section is missing.";return false;}
    QHash<qint64,FbxGeometry> geometries;QHash<qint64,QString> materials;QHash<qint64,FbxTexture> textures;QHash<qint64,FbxTexture> videos;
    for(const auto &node:objects->children){const qint64 id=fbxId(node);if(node.name=="Geometry"){FbxGeometry geometry;geometry.id=id;geometry.name=fbxName(fbxObjectName(node));const auto vertices=fbxNumbers(node,"Vertices"),polygons=fbxNumbers(node,"PolygonVertexIndex");for(int i=0;i+2<vertices.size();i+=3)geometry.positions<<QVector3D(vertices[i],vertices[i+1],vertices[i+2]);for(double value:polygons)geometry.polygon<<int(value);if(const auto *layer=fbxChild(node,"LayerElementUV")){const auto values=fbxNumbers(*layer,"UV"),indices=fbxNumbers(*layer,"UVIndex");for(int i=0;i+1<values.size();i+=2)geometry.uv<<QVector2D(values[i],values[i+1]);for(double value:indices)geometry.uvIndices<<int(value);}if(const auto *layer=fbxChild(node,"LayerElementMaterial"))for(double value:fbxNumbers(*layer,"Materials"))geometry.materialByPolygon<<int(value);if(!geometry.positions.isEmpty()&&!geometry.polygon.isEmpty())geometries.insert(id,std::move(geometry));}
        else if(node.name=="Material")materials.insert(id,fbxName(fbxObjectName(node)));
        else if(node.name=="Texture"){FbxTexture texture;texture.id=id;texture.name=fbxName(fbxObjectName(node));texture.file=fbxString(node,"RelativeFilename");if(texture.file.isEmpty())texture.file=fbxString(node,"FileName");textures.insert(id,std::move(texture));}
        else if(node.name=="Video"){FbxTexture video;video.id=id;video.name=fbxName(fbxObjectName(node));video.file=fbxString(node,"RelativeFilename");if(video.file.isEmpty())video.file=fbxString(node,"FileName");if(const auto *content=fbxChild(node,"Content"))if(!content->values.isEmpty())video.content=content->values.first().bytes;videos.insert(id,std::move(video));}}
    QHash<qint64,qint64> geometryToModel,materialToModel,videoToTexture,textureToMaterial;QHash<qint64,QString> textureProperty;
    if(connections)for(const auto &node:connections->children)if(node.name=="C"&&node.values.size()>=3){const QString type=node.values[0].text;const qint64 child=qint64(node.values[1].number),parent=qint64(node.values[2].number);const QString property=node.values.size()>3?node.values[3].text:QString{};if(geometries.contains(child)&&type=="OO")geometryToModel[child]=parent;else if(materials.contains(child)&&type=="OO")materialToModel[child]=parent;else if(videos.contains(child)&&textures.contains(parent)&&type=="OO")videoToTexture[child]=parent;else if(textures.contains(child)&&materials.contains(parent)){textureToMaterial[child]=parent;textureProperty[child]=property;}}
    for(auto it=videoToTexture.cbegin();it!=videoToTexture.cend();++it){auto texture=textures.value(it.value());const auto video=videos.value(it.key());if(texture.file.isEmpty())texture.file=video.file;if(texture.content.isEmpty())texture.content=video.content;textures[it.value()]=texture;}
    for(auto it=textures.cbegin();it!=textures.cend();++it){const qint64 materialId=textureToMaterial.value(it.key());if(!materials.contains(materialId))continue;const auto &texture=it.value();QString resolved=texture.file;if(!resolved.isEmpty()&&!QFileInfo(resolved).isAbsolute())resolved=QDir(QFileInfo(path).absolutePath()).filePath(resolved);if(!texture.content.isEmpty()){const QByteArray png=QByteArray::fromHex("89504e470d0a1a0a");const QString mime=texture.content.startsWith(png)?"image/png":"image/jpeg";resolved=cacheImage(path,int(it.key()&0x7fffffff),texture.content,mime);}appendFbxTexture(asset,materials.value(materialId),fbxSlot(textureProperty.value(it.key())),resolved);}
    QHash<qint64,QVector<qint64>> modelMaterials;for(auto it=materialToModel.cbegin();it!=materialToModel.cend();++it)modelMaterials[it.value()]<<it.key();
    auto materialIndex=[&](const QString &name){int index=asset.materials.indexOf(name);if(index<0){asset.materials<<name;index=asset.materials.size()-1;}return index;};
    for(auto geometryIt=geometries.cbegin();geometryIt!=geometries.cend();++geometryIt){const auto &geometry=geometryIt.value();const auto modelMaterialsForGeometry=modelMaterials.value(geometryToModel.value(geometry.id));int polygonStart=0,polygonOrdinal=0;QVector<int> face;QVector<int> sourceVertex;for(int encoded:geometry.polygon){const bool last=encoded<0;const int position=last?-encoded-1:encoded;if(position>=0&&position<geometry.positions.size()){const int polyVertex=polygonStart+face.size();int uvIndex=geometry.uvIndices.value(polyVertex,polyVertex);if(uvIndex<0||uvIndex>=geometry.uv.size())uvIndex=position<geometry.uv.size()?position:-1;asset.vertices.push_back({geometry.positions[position],uvIndex>=0?geometry.uv[uvIndex]:QVector2D{}});face<<asset.vertices.size()-1;sourceVertex<<position;}if(last){const int materialSlot=geometry.materialByPolygon.value(polygonOrdinal,0);const qint64 materialId=modelMaterialsForGeometry.value(materialSlot,modelMaterialsForGeometry.value(0));const int material=materials.contains(materialId)?materialIndex(materials.value(materialId)):-1;for(int i=1;i+1<face.size();++i)asset.triangles.push_back({face[0],face[i],face[i+1],material});polygonStart+=face.size();face.clear();sourceVertex.clear();++polygonOrdinal;}}
        asset.vertexCount+=geometry.positions.size();}
    asset.faceCount=asset.triangles.size();if(asset.vertices.isEmpty()){error="FBX contains no supported mesh geometry.";return false;}return true;
}

enum class AsciiTokenType { Word, String, Colon, Comma, Open, Close, Star, End };
struct AsciiToken { AsciiTokenType type=AsciiTokenType::End; QString value; };

class AsciiFbxLexer {
public:
    explicit AsciiFbxLexer(const QByteArray &source):data(QString::fromUtf8(source)){}
    AsciiToken next(){
        if(hasCached){hasCached=false;return cached;}
        while(position<data.size()){
            const QChar c=data[position];
            if(c==';'){while(position<data.size()&&data[position]!='\n')++position;continue;}
            if(c.isSpace()){++position;continue;}
            if(c==':'){++position;return {AsciiTokenType::Colon,{}};}if(c==','){++position;return {AsciiTokenType::Comma,{}};}if(c=='{'){++position;return {AsciiTokenType::Open,{}};}if(c=='}'){++position;return {AsciiTokenType::Close,{}};}if(c=='*'){++position;return {AsciiTokenType::Star,{}};}
            if(c=='\"'){++position;QString value;while(position<data.size()&&data[position]!='\"'){if(data[position]=='\\'&&position+1<data.size())++position;value+=data[position++];}if(position<data.size())++position;return {AsciiTokenType::String,value};}
            const int start=position;while(position<data.size()&&!data[position].isSpace()&&QString(":,{}*;\"").contains(data[position])==false)++position;return {AsciiTokenType::Word,data.mid(start,position-start)};
        }
        return {};
    }
    void putBack(AsciiToken token){cached=std::move(token);hasCached=true;}
private:
    QString data;int position=0;AsciiToken cached;bool hasCached=false;
};

bool asciiValue(const AsciiToken &token,FbxValue &value){
    if(token.type==AsciiTokenType::String){value.text=token.value;return true;}if(token.type!=AsciiTokenType::Word)return false;
    bool ok=false;const double number=token.value.toDouble(&ok);if(ok){value.numeric=true;value.number=number;value.numbers<<number;}else value.text=token.value;return true;
}

bool parseAsciiNodes(AsciiFbxLexer &lexer,QVector<FbxNode> &nodes,QString &error,bool inBlock){
    while(true){AsciiToken name=lexer.next();if(name.type==AsciiTokenType::End)return !inBlock;if(name.type==AsciiTokenType::Close)return inBlock;if(name.type!=AsciiTokenType::Word){continue;}const AsciiToken colon=lexer.next();if(colon.type!=AsciiTokenType::Colon){error="Invalid ASCII FBX node.";return false;}FbxNode node;node.name=name.value;
        if(node.name=="a"){
            while(true){AsciiToken token=lexer.next();if(token.type==AsciiTokenType::Close){nodes<<std::move(node);return true;}if(token.type==AsciiTokenType::End)break;if(token.type==AsciiTokenType::Comma||token.type==AsciiTokenType::Star)continue;FbxValue value;if(asciiValue(token,value))node.values<<value;}
            nodes<<std::move(node);return true;
        }
        bool opened=false;
        while(true){AsciiToken token=lexer.next();if(token.type==AsciiTokenType::End){nodes<<std::move(node);return !inBlock;}if(token.type==AsciiTokenType::Comma||token.type==AsciiTokenType::Star)continue;if(token.type==AsciiTokenType::Open){opened=true;break;}if(token.type==AsciiTokenType::Close){nodes<<std::move(node);return true;}FbxValue value;if(asciiValue(token,value))node.values<<value;
            const AsciiToken lookahead=lexer.next();if(lookahead.type==AsciiTokenType::Comma){continue;}if(lookahead.type==AsciiTokenType::Open){opened=true;break;}if(lookahead.type==AsciiTokenType::Close){nodes<<std::move(node);return true;}if(lookahead.type==AsciiTokenType::End){nodes<<std::move(node);return !inBlock;}if(lookahead.type==AsciiTokenType::Word){lexer.putBack(lookahead);break;}if(lookahead.type==AsciiTokenType::String){error="Invalid ASCII FBX property list.";return false;}
        }
        if(opened&&!parseAsciiNodes(lexer,node.children,error,true))return false;
        for(const auto &child:node.children)if(child.name=="a"){FbxValue array;for(const auto &entry:child.values)array.numbers+=entry.numbers;if(!array.numbers.isEmpty()){if(node.values.isEmpty())node.values<<array;else node.values[0].numbers=array.numbers;}}
        nodes<<std::move(node);
    }
}

bool parseAsciiFbx(const QByteArray &source,QVector<FbxNode> &roots,QString &error){
    const QByteArray header=source.left(128).toLower();if(!header.contains("fbx")){error="Invalid ASCII FBX header.";return false;}AsciiFbxLexer lexer(source);if(!parseAsciiNodes(lexer,roots,error,false))return false;bool objects=false;for(const auto &node:roots)if(node.name=="Objects"){objects=true;break;}if(!objects){error="ASCII FBX Objects section is missing.";return false;}return true;
}

bool loadFbx(const QString &path,ModelAsset &asset,QString &error){
    QFile file(path);if(!file.open(QIODevice::ReadOnly)){error="Cannot read FBX file.";return false;}const QByteArray source=file.readAll();const QByteArray signature("Kaydara FBX Binary  \0\x1a\0",23);
    if(!source.startsWith(signature)){QVector<FbxNode> roots;if(!parseAsciiFbx(source,roots,error))return false;return buildFbxAsset(path,roots,asset,error);}
    qsizetype offset=23;quint32 version=0;if(!fbxRead(source,offset,version)||version<7100){error="Unsupported FBX version.";return false;}QVector<FbxNode> roots;while(offset<source.size()){FbxNode node;if(!fbxNode(source,offset,int(version),node,error))return false;if(node.name.isEmpty())break;roots<<std::move(node);}return buildFbxAsset(path,roots,asset,error);
}
}

bool ModelImporter::load(const QString &path,ModelAsset &asset,QString &error){asset={};asset.sourcePath=path;const QString suffix=QFileInfo(path).suffix().toLower();if(suffix=="obj"){QFile file(path);if(!file.open(QIODevice::ReadOnly|QIODevice::Text)){error="Cannot read model file.";return false;}const QDir folder=QFileInfo(path).dir();QVector<QVector3D> positions;QVector<QVector2D> uvs;QStringList materialNames;auto materialIndex=[&](const QString &name){int index=materialNames.indexOf(name);if(index<0){materialNames<<name;index=materialNames.size()-1;}return index;};int currentMaterial=-1;auto resolve=[&](int index,int count){return index>0?index-1:(index<0?count+index:-1);};while(!file.atEnd()){const QString line=QString::fromUtf8(file.readLine()).trimmed();if(line.startsWith("v ")){const auto values=line.mid(2).split(QRegularExpression("\\s+"),Qt::SkipEmptyParts);if(values.size()>=3)positions.push_back({values[0].toFloat(),values[1].toFloat(),values[2].toFloat()});continue;}if(line.startsWith("vt ")){const auto values=line.mid(3).split(QRegularExpression("\\s+"),Qt::SkipEmptyParts);if(values.size()>=2)uvs.push_back({values[0].toFloat(),values[1].toFloat()});continue;}if(line.startsWith("usemtl ")){currentMaterial=materialIndex(line.mid(7).trimmed());continue;}if(line.startsWith("mtllib ")){appendMtl(folder.filePath(unquote(line.mid(7))),asset);continue;}if(!line.startsWith("f "))continue;const auto references=line.mid(2).split(QRegularExpression("\\s+"),Qt::SkipEmptyParts);QVector<int> face;for(const QString &reference:references){const auto parts=reference.split('/');const int position=resolve(parts.value(0).toInt(),positions.size()),uv=resolve(parts.value(1).toInt(),uvs.size());if(position<0||position>=positions.size())continue;asset.vertices.push_back({positions[position],uv>=0&&uv<uvs.size()?uvs[uv]:QVector2D{}});face<<asset.vertices.size()-1;}for(int i=1;i+1<face.size();++i)asset.triangles.push_back({face[0],face[i],face[i+1],currentMaterial});}asset.vertexCount=positions.size();asset.faceCount=asset.triangles.size();return true;}QByteArray json,bin;if(suffix=="gltf"){QFile file(path);if(!file.open(QIODevice::ReadOnly)){error="Cannot read glTF file.";return false;}json=file.readAll();return loadGltf(path,json,{},asset,error);}if(suffix=="glb"){if(!readGlb(path,json,bin,error))return false;return loadGltf(path,json,bin,asset,error);}if(suffix=="fbx")return loadFbx(path,asset,error);error="Supported model formats: OBJ/MTL, glTF, GLB, and FBX embedded image extraction.";return false;}

int ModelImporter::extractTextures(const ModelAsset &asset,const QString &folder,QString &error){QDir().mkpath(folder);int count=0;for(const auto &texture:asset.textures){if(!QFileInfo::exists(texture.path))continue;const QString base=QFileInfo(texture.path).fileName();QString target=QDir(folder).filePath(base);int copy=2;while(QFileInfo::exists(target))target=QDir(folder).filePath(QFileInfo(base).completeBaseName()+"_"+QString::number(copy++)+"."+QFileInfo(base).suffix());if(QFile::copy(texture.path,target))++count;}if(!count)error="No texture files could be extracted.";return count;}
