#include "MainWindow.h"
#include "MaterialViewport.h"
#include <cmath>
#include <stdexcept>
namespace {
void require(bool condition,const QString &message){if(!condition)throw std::runtime_error(message.toUtf8().constData());}
void spin(int ms){QElapsedTimer timer;timer.start();while(timer.elapsed()<ms){QCoreApplication::processEvents(QEventLoop::AllEvents,10);QThread::msleep(5);}}
QImage legacyLevels(const QImage &input,const Adjustments &a){
    QImage image=input.copy();
    for(int y=0;y<image.height();++y){auto *line=(QRgb*)image.scanLine(y);for(int x=0;x<image.width();++x){QColor c=QColor::fromRgba(line[x]);float h,s,v;c.getHsvF(&h,&s,&v);h=float(std::fmod(std::max(0.f,h)+a.hue/360.+1,1));c.setHsvF(h,float(std::clamp(s*a.saturation,0.,1.)),float(std::clamp(v+a.brightness,0.,1.)),c.alphaF());auto level=[&](double n,double balance){return qRound(std::clamp(std::pow(std::clamp((n-a.blacks)/std::max(.001,a.whites-a.blacks),0.,1.),1/a.gamma)+balance,0.,1.)*255);};line[x]=qRgba(level(c.redF(),a.red),level(c.greenF(),a.green),level(c.blueF(),a.blue),c.alpha());}}
    return image;
}
}
int runUpgradeTests(){
    QStringList report;try{
        QTemporaryDir modelTemp;QImage modelImage(8,8,QImage::Format_RGBA8888);modelImage.fill(Qt::green);require(modelImage.save(modelTemp.filePath("surface.png")),"Model texture fixture failed");QFile materialFile(modelTemp.filePath("mesh.mtl"));require(materialFile.open(QIODevice::WriteOnly|QIODevice::Text),"Model MTL fixture failed");materialFile.write("newmtl Surface\nmap_Kd surface.png\nmap_Bump surface.png\n");materialFile.close();QFile objectFile(modelTemp.filePath("mesh.obj"));require(objectFile.open(QIODevice::WriteOnly|QIODevice::Text),"Model OBJ fixture failed");objectFile.write("mtllib mesh.mtl\nv 0 0 0\nv 1 0 0\nv 0 1 0\nvt 0 0\nvt 1 0\nvt 0 1\nf 1/1 2/2 3/3\n");objectFile.close();ModelAsset modelAsset;QString modelError;require(ModelImporter::load(modelTemp.filePath("mesh.obj"),modelAsset,modelError),modelError);require(modelAsset.vertexCount==3&&modelAsset.faceCount==1&&modelAsset.textures.size()==2&&modelAsset.vertices.size()==3&&modelAsset.triangles.size()==1,"Model material texture/mesh discovery failed");MaterialViewport meshView;meshView.setMesh(&modelAsset);meshView.setMaterial(modelImage);const QImage meshImage=meshView.renderPreview({180,180});require(meshImage.pixelColor(90,90)!=QColor("#0b1118"),"UV mesh preview failed");const QString extracted=QDir(modelTemp.path()).filePath("extracted");require(ModelImporter::extractTextures(modelAsset,extracted,modelError)==2,modelError);report<<"PASS: native OBJ/MTL material slots, UV mesh, and texture extraction";
        const QString blenderObj="C:/Users/rmart/Reign of Glory/Character Creator 4/base/caleb model_base_xxx.obj";if(QFileInfo::exists(blenderObj)){ModelAsset blenderAsset;QString blenderError;require(ModelImporter::load(blenderObj,blenderAsset,blenderError),blenderError);require(!blenderAsset.vertices.isEmpty()&&!blenderAsset.triangles.isEmpty(),"Blender OBJ mesh extraction failed");report<<QString("PASS: Blender OBJ mesh import · %1 triangles").arg(blenderAsset.triangles.size());}
        const QString blenderFbx="C:/Users/rmart/Reign of Glory/blender/fence/fbx/reign of glory - door hinge.fbx";if(QFileInfo::exists(blenderFbx)){ModelAsset blenderFbxAsset;QString blenderFbxError;require(ModelImporter::load(blenderFbx,blenderFbxAsset,blenderFbxError),blenderFbxError);require(!blenderFbxAsset.vertices.isEmpty()&&!blenderFbxAsset.triangles.isEmpty(),"Blender FBX mesh extraction failed");report<<QString("PASS: Blender binary FBX mesh import · %1 vertices · %2 triangles · %3 materials").arg(blenderFbxAsset.vertices.size()).arg(blenderFbxAsset.triangles.size()).arg(blenderFbxAsset.materials.size());}
        QFile asciiFbx(modelTemp.filePath("triangle-ascii.fbx"));require(asciiFbx.open(QIODevice::WriteOnly|QIODevice::Text),"ASCII FBX fixture failed");asciiFbx.write("; FBX 7.4.0 project file\nObjects: {\n Geometry: 1, \"Geometry::Triangle\", \"Mesh\" {\n  Vertices: *9 { a: 0,0,0,1,0,0,0,1,0 }\n  PolygonVertexIndex: *3 { a: 0,1,-3 }\n  LayerElementUV: 0 { UV: *6 { a: 0,0,1,0,0,1 } UVIndex: *3 { a: 0,1,2 } }\n }\n Model: 4, \"Model::Triangle\", \"Mesh\" { }\n Material: 2, \"Material::Surface\", \"\" { }\n Texture: 3, \"Texture::Diffuse\", \"\" { RelativeFilename: \"surface.png\" }\n}\nConnections: {\n C: \"OO\",1,4\n C: \"OO\",2,4\n C: \"OP\",3,2,\"DiffuseColor\"\n}\n");asciiFbx.close();ModelAsset asciiAsset;QString asciiError;require(ModelImporter::load(asciiFbx.fileName(),asciiAsset,asciiError),asciiError);require(asciiAsset.vertices.size()==3&&asciiAsset.triangles.size()==1&&asciiAsset.materials.size()==1&&asciiAsset.textures.size()==1,"ASCII FBX mesh/material graph failed");report<<"PASS: native ASCII FBX mesh, UV, material and texture graph";
        QTemporaryDir temp;QImage source(120,80,QImage::Format_ARGB32);source.fill(QColor(180,60,30));Adjustments a;a.padding={.1,.2,.1,.2};
        auto padded=ImageProcessor::render(source,{100,100},a);require(qAlpha(padded.pixel(0,0))==0&&qAlpha(padded.pixel(50,50))==255,"Padding alpha failed");
        a.overlay=true;a.overlayColor=Qt::blue;a.effectOpacity=1;auto overlay=ImageProcessor::render(source,{100,100},a);require(qBlue(overlay.pixel(50,50))==255&&qRed(overlay.pixel(50,50))==0,"Live color overlay failed");
        a.overlay=false;a.stroke=true;a.strokeSize=.04;a.strokeColor=Qt::yellow;auto stroke=ImageProcessor::render(source,{100,100},a);require(qAlpha(stroke.pixel(8,50))>0&&qRed(stroke.pixel(8,50))==255,"Outside stroke failed");
        a.stroke=false;a.shadow=true;a.glow=true;a.innerShadow=true;a.bevel=true;a.opacity=.5;auto effects=ImageProcessor::render(source,{100,100},a);require(!effects.isNull()&&qAlpha(effects.pixel(50,50))<=128,"Layer effects / opacity failed");report<<"PASS: live padding, overlays, stroke, glow, shadows, bevel and opacity";
        source.save(temp.filePath("image.png"));ExportJob job;job.files={temp.filePath("image.png")};job.sizes={{32,32},{64,64}};job.imageFormats={"PNG","JPG","BMP"};job.outputRoot=temp.path();job.zip=true;job.workers=2;std::atomic_bool cancel{false};
        auto result=ExportManager::run(job,cancel,[](int,int,QString){});require(result.error.isEmpty(),result.error);require(result.written==6,"Multi-format image count failed");for(const auto &format:job.imageFormats)require(ImageProcessor::read(result.folder+"/64/image."+format.toLower()).size()==QSize(64,64),"Image format dimensions failed");report<<"PASS: six outputs across two sizes and three image formats";
        QString tool=qEnvironmentVariable("ASPECTRA_TEST_FFMPEG"),root=qEnvironmentVariable("ASPECTRA_TEST_OUTPUT");
        if(!tool.isEmpty()&&!root.isEmpty()){
            QString video=QDir(root).filePath("video-test-source.mp4");ExportJob vjob;vjob.files={video};vjob.outputRoot=root;vjob.ffmpeg=tool;vjob.sizes={{64,36}};vjob.videoFormats={"MP4","MOV","WEBM","GIF"};vjob.clips[video]={{"First",0,.3,true},{"Second",.5,.9,true},{"Disabled",.1,.2,false}};vjob.workers=2;vjob.zip=true;
            auto vr=ExportManager::run(vjob,cancel,[](int,int,QString){});require(vr.error.isEmpty(),vr.error);require(vr.written==8,"Clip/format output count failed");QDirIterator files(vr.folder,{"*.mp4","*.mov","*.webm","*.gif"},QDir::Files,QDirIterator::Subdirectories);while(files.hasNext()){auto media=VideoProcessor::inspect(tool,files.next());require(media.size==QSize(64,36)&&media.duration>0&&media.duration<.7,"Clip dimensions/duration failed");}
            report<<"PASS: two enabled clips × MP4/MOV/WEBM/GIF; correct dimensions and durations";
            vjob.videoFormats={"MP4"};vjob.clips[video]={{"Styled",.1,.4,true}};vjob.adjustments=a;vjob.adjustments.saturation=.6;vjob.zip=false;auto styled=ExportManager::run(vjob,cancel,[](int,int,QString){});require(styled.error.isEmpty(),styled.error);require(styled.written==1,"Styled video export failed");report<<"PASS: styled video with padding and live color pipeline";
        }
        QImage large(1920,1080,QImage::Format_ARGB32);large.fill(QColor(170,90,35));Adjustments levels;levels.gamma=1.2;levels.blacks=.04;levels.whites=.95;
        QElapsedTimer timer;timer.start();auto oldImage=legacyLevels(large,levels);qint64 before=timer.nsecsElapsed();timer.restart();auto fastImage=ImageProcessor::render(large,large.size(),levels);qint64 after=timer.nsecsElapsed();require(oldImage.pixel(500,500)==fastImage.pixel(500,500),"Optimized level values diverged");
        report<<QString("BENCHMARK 1920×1080 levels: old %1 ms; new %2 ms; %3× faster in this run").arg(before/1000000.,0,'f',1).arg(after/1000000.,0,'f',1).arg(double(before)/std::max<qint64>(1,after),0,'f',2);
        QFile file(QDir::current().filePath("upgrade-test-result.txt"));if(file.open(QIODevice::WriteOnly))file.write(report.join('\n').toUtf8());return 0;
    }catch(const std::exception &e){report<<"FAIL: "+QString::fromUtf8(e.what());QFile file(QDir::current().filePath("upgrade-test-result.txt"));if(file.open(QIODevice::WriteOnly))file.write(report.join('\n').toUtf8());return 1;}
}
int runUiTests(MainWindow &w){
    QStringList report;try{
        spin(50);TopBar *topBar=nullptr;for(auto *child:w.findChildren<QWidget*>())if(auto *candidate=dynamic_cast<TopBar*>(child)){topBar=candidate;break;}require(topBar&&topBar->backButton,"Top bar controls missing");auto *headerLogo=topBar->findChild<QLabel*>("HeaderLogo");auto *headerActions=topBar->findChild<QWidget*>("HeaderActions");require(QFile::exists(":/brand/wordmark.png")&&!w.windowIcon().isNull(),"Embedded header or taskbar brand asset missing");require(topBar->backButton->mapTo(topBar,QPoint{}).x()==0,"Back control is not flush to the header's left edge");require(headerLogo&&qAbs(headerLogo->geometry().center().x()-topBar->rect().center().x())<=1,"Header wordmark is not centered");require(headerActions&&headerActions->geometry().right()==topBar->rect().right(),"Header action cluster is not right-aligned");require(!topBar->titleLabel->isVisible(),"Header text must stay hidden when the centered logo is used");report<<"PASS: locked centered logo header, taskbar icon, Back and right action cluster";
        QTemporaryDir temp;QImage a(100,80,QImage::Format_ARGB32);a.fill(Qt::red);a.save(temp.filePath("red.png"));a.fill(Qt::blue);a.save(temp.filePath("blue.png"));w.loadFiles({temp.filePath("red.png"),temp.filePath("blue.png")});
        auto waitLoad=[&]{QElapsedTimer timer;timer.start();while(w.loading&&timer.elapsed()<15000)spin(10);require(!w.loading,"UI load timed out");spin(100);};waitLoad();require(w.batch.files.size()==2,"Navigation batch failed");w.navigate(1);waitLoad();require(w.currentFile.endsWith("blue.png"),"Next navigation failed");w.navigate(-1);waitLoad();require(w.currentFile.endsWith("red.png"),"Previous navigation failed");
        w.paddingInputs[0]->setValue(15);w.paddingInputs[2]->setValue(15);w.sliders["saturation"]->setValue(0);spin(100);auto image=w.preview->rendered();QColor pixel=image.pixelColor(image.width()/2,image.height()/2);require(pixel.red()==pixel.green()&&pixel.green()==pixel.blue(),"Color controls did not update live");require(qAlpha(image.pixel(0,0))==0,"Live padding failed");
        w.styleChecks["overlay"]->setChecked(true);w.layerStyle.overlayColor=Qt::green;w.layerStyle.effectOpacity=1;w.refresh();spin(100);pixel=w.preview->rendered().pixelColor(image.width()/2,image.height()/2);require(pixel.green()==255&&pixel.red()==0,"Live style controls failed");report<<"PASS: previous/next navigation, live color, padding and style controls";
        w.marginUnits->setCurrentIndex(1);w.paddingInputs[0]->setValue(12);w.safeInputs[0]->setValue(10);const double expectedPadding=12./w.widthInput->value();require(qAbs(w.adjustments().padding.left()-expectedPadding)<.0001,"Pixel padding did not normalize to the output canvas");w.marginUnits->setCurrentIndex(0);report<<"PASS: safe and red guide regions stay canvas-relative in pixel and percent units";
        {
            auto *safeSlider=w.findChild<QSlider*>("SafeZoneSlider");
            require(safeSlider&&safeSlider->isVisible(),"Safe-zone slider missing");
            auto sendSafeMouse=[&](QEvent::Type type,qreal fraction){
                const QPointF local(safeSlider->width()/2.0,8+(safeSlider->height()-16)*fraction);
                const QPointF global=safeSlider->mapToGlobal(local.toPoint());
                if(type==QEvent::MouseButtonPress)
                    require(w.childAt(w.mapFromGlobal(global.toPoint()))==safeSlider,"Preview intercepts safe-zone slider clicks");
                QMouseEvent event(type,local,global,type==QEvent::MouseMove?Qt::NoButton:Qt::LeftButton,
                                  type==QEvent::MouseButtonRelease?Qt::NoButton:Qt::LeftButton,Qt::NoModifier);
                QCoreApplication::sendEvent(safeSlider,&event);
            };
            w.guides->setChecked(false);
            sendSafeMouse(QEvent::MouseButtonPress,.8);
            sendSafeMouse(QEvent::MouseMove,.3);
            sendSafeMouse(QEvent::MouseButtonRelease,.3);
            require(qAbs(safeSlider->value()-31.5)<=.5,QString("Safe-zone drag expected 31 or 32, received %1").arg(safeSlider->value()));
            for(auto *input:w.safeInputs)require(qAbs(input->value()-safeSlider->value())<.01,"Safe-zone drag did not update all edges");
            require(w.guides->isChecked(),"Safe-zone drag did not reveal guides");
            w.marginUnits->setCurrentIndex(1);
            sendSafeMouse(QEvent::MouseButtonPress,.7);
            sendSafeMouse(QEvent::MouseMove,.5);
            sendSafeMouse(QEvent::MouseButtonRelease,.5);
            const QMarginsF margins=w.normalizedMargins(w.safeInputs);
            for(double margin:{margins.left(),margins.top(),margins.right(),margins.bottom()})
                require(qAbs(margin-safeSlider->value()/100.0)<.002,"Safe-zone slider used pixels instead of percentages");
            w.marginUnits->setCurrentIndex(0);
            safeSlider->setValue(10);
            report<<"PASS: safe-zone pointer hit, drag, all four margins, guide visibility and pixel-unit conversion";
        }
        TimelineTrack text;text.type=TimelineTrack::Text;text.name="Title";text.text="Title";text.start=0;text.end=1;w.timelineTracks<<text;w.updateTrackPanel();w.trackList->setCurrentRow(w.timelineTracks.size()-1);spin(30);require(w.timelineTracks.last().text=="Title","Text layer data was lost");report<<"PASS: text-layer data remains without a bottom card";
        const int beforePlacedText=w.timelineTracks.size();w.preview->setCanvasTool(CanvasTool::Type);const QPoint textPoint=w.preview->rect().center();QMouseEvent textPress(QEvent::MouseButtonPress,QPointF(textPoint),QPointF(w.preview->mapToGlobal(textPoint)),Qt::LeftButton,Qt::LeftButton,Qt::NoModifier);QMouseEvent textRelease(QEvent::MouseButtonRelease,QPointF(textPoint),QPointF(w.preview->mapToGlobal(textPoint)),Qt::LeftButton,Qt::NoButton,Qt::NoModifier);QCoreApplication::sendEvent(w.preview,&textPress);QCoreApplication::sendEvent(w.preview,&textRelease);spin(30);require(w.timelineTracks.size()==beforePlacedText+1&&w.timelineTracks.last().type==TimelineTrack::Text&&w.trackList->currentRow()==w.timelineTracks.size()-1,"Type tool click did not place and select text");report<<"PASS: Type tool places and selects text at the preview click";
        w.tabs->setCurrentIndex(3);spin(10);w.tracePreviewActive=true;w.pendingTraceSvg="<svg/>";w.pendingTraceColors=5;w.preview->setVectorTraceFrame(QImage(12,12,QImage::Format_ARGB32));w.tabs->setCurrentIndex(0);spin(15);require(!w.tracePreviewActive&&w.pendingTraceSvg.isEmpty()&&w.pendingTraceColors==0,"Leaving Trace did not clear the preview state");report<<"PASS: leaving Trace clears yellow trace-preview state";
        QString gallery=qEnvironmentVariable("ASPECTRA_TEST_GALLERY");
        if(!gallery.isEmpty()){QDir().mkpath(gallery);for(int i=0;i<w.tabs->count();++i){w.tabs->setCurrentIndex(i);spin(100);w.savePreview(QDir(gallery).filePath(QString("image-section-%1.png").arg(i)));}}
        w.tabs->setCurrentIndex(6);spin(50);auto findTextureRail=[&](const QString &name){for(auto *button:w.findChildren<QToolButton*>("SubRailIcon"))if(button->toolTip()==name)return button;return static_cast<QToolButton*>(nullptr);};auto *sphere=findTextureRail("Sphere");require(sphere,"Sphere texture rail control missing");sphere->click();spin(20);auto *base=findTextureRail("Base Color");require(base,"Base Color texture rail control missing after Sphere");base->click();spin(20);require(w.textureMapPreview&&w.textureMapPreview->currentText()=="Base Color","Texture map card did not restore Base Color after Sphere");sphere=findTextureRail("Sphere");require(sphere,"Sphere texture rail control missing after Base Color");sphere->click();spin(20);auto *rma=findTextureRail("RMA");require(rma,"RMA texture rail control missing after Sphere");rma->click();spin(20);require(w.textureMapPreview&&w.textureMapPreview->currentText()=="RMA","Texture map card did not restore RMA after Sphere");report<<"PASS: Sphere card clears before texture-map controls";
        w.preview->setViewZoom(1.5);spin(150);auto *focusShell=w.findChild<QWidget*>("shell");const QString focusParent=w.preview->parentWidget()?w.preview->parentWidget()->objectName():"<null>";require(focusShell&&w.preview->parentWidget()==focusShell&&w.preview->geometry()==focusShell->rect(),QString("Focus zoom promotion mismatch · parent %1 · image %2,%3 %4×%5 · shell %6×%7").arg(focusParent).arg(w.preview->geometry().x()).arg(w.preview->geometry().y()).arg(w.preview->geometry().width()).arg(w.preview->geometry().height()).arg(focusShell?focusShell->width():-1).arg(focusShell?focusShell->height():-1));const QRectF focusFrame=w.preview->displayedFrameRect();const QRectF focusViewport=w.preview->rect();require(focusFrame.left()<=focusViewport.left()&&focusFrame.right()>=focusViewport.right()&&focusFrame.top()<=focusViewport.top()&&focusFrame.bottom()>=focusViewport.bottom(),"Focus zoom left a black margin around the image");if(!gallery.isEmpty())w.savePreview(QDir(gallery).filePath("focus-zoom-cover.png"));w.preview->setViewZoom(1.0);spin(50);require(w.preview->parentWidget()&&w.preview->parentWidget()->objectName()=="MainPreview","Focus zoom did not restore the normal preview hierarchy");report<<"PASS: phone-style focus zoom promotes a sharp edge-to-edge preview";
        w.showExportWindow();spin(50);if(!gallery.isEmpty())w.exportDialog->grab().save(QDir(gallery).filePath("export-window.png"));require(w.exportDialog->isVisible(),"Export overlay not visible");w.exportDialog->hide();report<<"PASS: separate export overlay";
        QString video=QDir(qEnvironmentVariable("ASPECTRA_TEST_OUTPUT")).filePath("video-test-source.mp4");if(QFileInfo::exists(video)){
            w.loadFiles({video});waitLoad();w.inMarker->setValue(.1);w.outMarker->setValue(.3);w.addClip();w.inMarker->setValue(.5);w.outMarker->setValue(.8);w.addClip();require(w.clips.value(video).size()==2,"UI multi-clip markers failed");QElapsedTimer readyTimer;readyTimer.start();while(w.player->duration()==0&&readyTimer.elapsed()<10000)spin(25);w.player->setPosition(100);w.player->play();qint64 furthest=0;QElapsedTimer playing;playing.start();while(playing.elapsed()<2500){spin(25);furthest=std::max(furthest,w.player->position());}w.player->pause();require(w.player->error()==QMediaPlayer::NoError,"Video player error: "+w.player->errorString());require(furthest>=200,QString("Video player did not advance: duration %1, position %2, status %3").arg(w.player->duration()).arg(furthest).arg(int(w.player->mediaStatus())));if(!gallery.isEmpty()){w.tabs->setCurrentIndex(3);spin(100);w.savePreview(QDir(gallery).filePath("video-clips.png"));}report<<"PASS: playable video, seek and two separate marker ranges";
        }
        QFile file(QDir::current().filePath("ui-test-result.txt"));if(file.open(QIODevice::WriteOnly))file.write(report.join('\n').toUtf8());return 0;
    }catch(const std::exception &e){report<<"FAIL: "+QString::fromUtf8(e.what());QFile file(QDir::current().filePath("ui-test-result.txt"));if(file.open(QIODevice::WriteOnly))file.write(report.join('\n').toUtf8());return 1;}
}
int runFocusZoomTest(MainWindow &w){
    QStringList report;
    class MouseTrace final : public QObject {
    public:
        QStringList events;
        bool eventFilter(QObject *object,QEvent *event) override {
            if(event->type()==QEvent::MouseButtonPress||event->type()==QEvent::MouseMove||event->type()==QEvent::MouseButtonRelease){
                events<<QString("%1:%2").arg(object->objectName()).arg(int(event->type()));
                if(events.size()>18)events.removeFirst();
            }
            return false;
        }
    } mouseTrace;
    qApp->installEventFilter(&mouseTrace);
    try{
        QTemporaryDir temp;QImage source(120,80,QImage::Format_ARGB32);source.fill(Qt::red);require(source.save(temp.filePath("focus.png")),"Focus fixture failed");
        w.loadFiles({temp.filePath("focus.png")});QElapsedTimer timer;timer.start();while(w.loading&&timer.elapsed()<15000)spin(10);require(!w.loading,"Focus fixture load timed out");spin(120);require(w.widthInput->value()==120&&w.heightInput->value()==80,"Imported media dimensions did not become the canvas dimensions");
        w.preview->setViewZoom(1.5);spin(340);auto *shell=w.findChild<QWidget*>("shell");require(shell&&w.preview->parentWidget()==shell&&w.preview->geometry()==shell->rect(),"Focus zoom did not promote the preview to the full client viewport");
        const QRectF image=w.preview->displayedFrameRect(),viewport=w.preview->rect();require(image.left()<=viewport.left()&&image.right()>=viewport.right()&&image.top()<=viewport.top()&&image.bottom()>=viewport.bottom(),"Focus zoom did not cover all four preview edges");
        w.preview->setViewZoom(8.0);spin(100);require(w.preview->displayedFrameRect().width()>image.width()*3,"Focus zoom stopped before continuing deeper into the image");
        const QRectF beforePan=w.preview->displayedFrameRect();const QPoint panStart=w.preview->rect().center(),panEnd=panStart+QPoint(36,24);
        QMouseEvent press(QEvent::MouseButtonPress,QPointF(panStart),QPointF(w.preview->mapToGlobal(panStart)),Qt::LeftButton,Qt::LeftButton,Qt::NoModifier);
        QMouseEvent move(QEvent::MouseMove,QPointF(panEnd),QPointF(w.preview->mapToGlobal(panEnd)),Qt::NoButton,Qt::LeftButton,Qt::NoModifier);
        QMouseEvent release(QEvent::MouseButtonRelease,QPointF(panEnd),QPointF(w.preview->mapToGlobal(panEnd)),Qt::LeftButton,Qt::NoButton,Qt::NoModifier);
        QCoreApplication::sendEvent(w.preview,&press);QCoreApplication::sendEvent(w.preview,&move);QCoreApplication::sendEvent(w.preview,&release);spin(30);
        const QRectF afterPan=w.preview->displayedFrameRect();require(afterPan.center().x()>beforePan.center().x()+20&&afterPan.center().y()>beforePan.center().y()+12,"Focus canvas drag did not pan the live image");
        QWidget hitTestOverlay(shell);hitTestOverlay.setGeometry(shell->rect().adjusted(100,180,-100,-180));hitTestOverlay.show();const QRectF beforeOverlayPan=w.preview->displayedFrameRect();const QPoint overlayStart=hitTestOverlay.rect().center(),overlayEnd=overlayStart+QPoint(32,20);
        QMouseEvent overlayPress(QEvent::MouseButtonPress,QPointF(overlayStart),QPointF(hitTestOverlay.mapToGlobal(overlayStart)),Qt::LeftButton,Qt::LeftButton,Qt::NoModifier);
        QMouseEvent overlayMove(QEvent::MouseMove,QPointF(overlayEnd),QPointF(hitTestOverlay.mapToGlobal(overlayEnd)),Qt::NoButton,Qt::LeftButton,Qt::NoModifier);
        QMouseEvent overlayRelease(QEvent::MouseButtonRelease,QPointF(overlayEnd),QPointF(hitTestOverlay.mapToGlobal(overlayEnd)),Qt::LeftButton,Qt::NoButton,Qt::NoModifier);
        QCoreApplication::sendEvent(&hitTestOverlay,&overlayPress);QCoreApplication::sendEvent(&hitTestOverlay,&overlayMove);QCoreApplication::sendEvent(&hitTestOverlay,&overlayRelease);spin(30);hitTestOverlay.hide();
        const QRectF afterOverlayPan=w.preview->displayedFrameRect();require(afterOverlayPan.center().x()>beforeOverlayPan.center().x()+18&&afterOverlayPan.center().y()>beforeOverlayPan.center().y()+10,QString("Focus overlay drag delta %1,%2; zoom %3; parent %4; focus %5").arg(afterOverlayPan.center().x()-beforeOverlayPan.center().x()).arg(afterOverlayPan.center().y()-beforeOverlayPan.center().y()).arg(w.preview->viewZoomValue()).arg(w.preview->parentWidget()->objectName()).arg(QApplication::focusWidget()?QApplication::focusWidget()->objectName():QString("none")));
        const QImage focusCapture=w.grab().toImage();const QColor focusCenter=focusCapture.pixelColor(focusCapture.width()/2,focusCapture.height()/2);require(focusCenter.red()>200&&focusCenter.green()<80&&focusCenter.blue()<80,"Focus zoom image is occluded by a black panel surface");focusCapture.save(QDir::current().filePath("focus-zoom-test.png"));
        w.preview->setViewZoom(16.0);spin(30);const QPoint wheelPoint=w.preview->rect().center();for(int step=0;step<16;++step){QWheelEvent touchpadWheel(QPointF(wheelPoint),QPointF(w.preview->mapToGlobal(wheelPoint)),QPoint(0,-15),QPoint(),Qt::NoButton,Qt::NoModifier,Qt::NoScrollPhase,false);QCoreApplication::sendEvent(w.preview,&touchpadWheel);}spin(100);require(w.preview->parentWidget()&&w.preview->parentWidget()->objectName()=="MainPreview","Touchpad zoom-out did not restore the normal canvas");report<<"PASS: focus canvas fills the app, pans live, supports touchpad zoom-out, and returns to canvas";
    }catch(const std::exception &e){report<<"FAIL: "+QString::fromUtf8(e.what());report<<mouseTrace.events.join(", ");}
    QFile file(QDir::current().filePath("focus-zoom-test-result.txt"));if(file.open(QIODevice::WriteOnly))file.write(report.join('\n').toUtf8());return report.value(0).startsWith("PASS")?0:1;
}
